# Generated by Django 4.2.2 on 2023-06-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
